# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'converter.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_converter(object):
    def setupUi(self, converter):
        converter.setObjectName("converter")
        converter.setWindowModality(QtCore.Qt.ApplicationModal)
        converter.resize(634, 729)
        converter.setMinimumSize(QtCore.QSize(634, 729))
        converter.setMaximumSize(QtCore.QSize(634, 729))
        self.centralwidget = QtWidgets.QWidget(converter)
        self.centralwidget.setObjectName("centralwidget")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(530, 90, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton.setFont(font)
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.toolButton.setAcceptDrops(False)
        self.toolButton.setToolTip("")
        self.toolButton.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton.setObjectName("toolButton")
        self.codec_group = QtWidgets.QGroupBox(self.centralwidget)
        self.codec_group.setGeometry(QtCore.QRect(20, 380, 591, 111))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.codec_group.setFont(font)
        self.codec_group.setObjectName("codec_group")
        self.vcodecs_dropdown = QtWidgets.QComboBox(self.codec_group)
        self.vcodecs_dropdown.setGeometry(QtCore.QRect(10, 40, 571, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.vcodecs_dropdown.setFont(font)
        self.vcodecs_dropdown.setObjectName("vcodecs_dropdown")
        self.vcodec_label = QtWidgets.QLabel(self.codec_group)
        self.vcodec_label.setGeometry(QtCore.QRect(10, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.vcodec_label.setFont(font)
        self.vcodec_label.setObjectName("vcodec_label")
        self.acodec_label = QtWidgets.QLabel(self.codec_group)
        self.acodec_label.setGeometry(QtCore.QRect(10, 60, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.acodec_label.setFont(font)
        self.acodec_label.setObjectName("acodec_label")
        self.acodecs_dropdown = QtWidgets.QComboBox(self.codec_group)
        self.acodecs_dropdown.setGeometry(QtCore.QRect(10, 80, 571, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.acodecs_dropdown.setFont(font)
        self.acodecs_dropdown.setObjectName("acodecs_dropdown")
        self.ETA_label = QtWidgets.QLabel(self.centralwidget)
        self.ETA_label.setGeometry(QtCore.QRect(460, 119, 41, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ETA_label.setFont(font)
        self.ETA_label.setObjectName("ETA_label")
        self.update_label = QtWidgets.QLabel(self.centralwidget)
        self.update_label.setGeometry(QtCore.QRect(400, 90, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.update_label.setFont(font)
        self.update_label.setObjectName("update_label")
        self.file_list_label = QtWidgets.QLabel(self.centralwidget)
        self.file_list_label.setGeometry(QtCore.QRect(20, 119, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.file_list_label.setFont(font)
        self.file_list_label.setObjectName("file_list_label")
        self.time_label = QtWidgets.QLabel(self.centralwidget)
        self.time_label.setGeometry(QtCore.QRect(500, 119, 111, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.time_label.setFont(font)
        self.time_label.setObjectName("time_label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 650, 581, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.convert_btn = QtWidgets.QPushButton(self.centralwidget)
        self.convert_btn.setEnabled(True)
        self.convert_btn.setGeometry(QtCore.QRect(530, 680, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.convert_btn.setFont(font)
        self.convert_btn.setObjectName("convert_btn")
        self.close_btn = QtWidgets.QPushButton(self.centralwidget)
        self.close_btn.setGeometry(QtCore.QRect(30, 680, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.close_btn.setFont(font)
        self.close_btn.setObjectName("close_btn")
        self.logo_label = QtWidgets.QLabel(self.centralwidget)
        self.logo_label.setGeometry(QtCore.QRect(-10, -40, 351, 151))
        self.logo_label.setObjectName("logo_label")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(20, 250, 61, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.clear_btn.setFont(font)
        self.clear_btn.setObjectName("clear_btn")
        self.header_label = QtWidgets.QLabel(self.centralwidget)
        self.header_label.setGeometry(QtCore.QRect(350, 20, 281, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(26)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.header_label.setFont(font)
        self.header_label.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.header_label.setObjectName("header_label")
        self.parameter_group = QtWidgets.QGroupBox(self.centralwidget)
        self.parameter_group.setGeometry(QtCore.QRect(20, 490, 591, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.parameter_group.setFont(font)
        self.parameter_group.setObjectName("parameter_group")
        self.frame_rate_label = QtWidgets.QLabel(self.parameter_group)
        self.frame_rate_label.setGeometry(QtCore.QRect(10, 20, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_rate_label.setFont(font)
        self.frame_rate_label.setObjectName("frame_rate_label")
        self.frame_rate_inp = QtWidgets.QLineEdit(self.parameter_group)
        self.frame_rate_inp.setGeometry(QtCore.QRect(90, 20, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.frame_rate_inp.setFont(font)
        self.frame_rate_inp.setObjectName("frame_rate_inp")
        self.audio_bitrate_label = QtWidgets.QLabel(self.parameter_group)
        self.audio_bitrate_label.setGeometry(QtCore.QRect(260, 20, 101, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.audio_bitrate_label.setFont(font)
        self.audio_bitrate_label.setObjectName("audio_bitrate_label")
        self.audio_bitrate_inp = QtWidgets.QLineEdit(self.parameter_group)
        self.audio_bitrate_inp.setGeometry(QtCore.QRect(350, 20, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.audio_bitrate_inp.setFont(font)
        self.audio_bitrate_inp.setObjectName("audio_bitrate_inp")
        self.crf_label = QtWidgets.QLabel(self.parameter_group)
        self.crf_label.setGeometry(QtCore.QRect(160, 20, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.crf_label.setFont(font)
        self.crf_label.setObjectName("crf_label")
        self.crf_inp = QtWidgets.QLineEdit(self.parameter_group)
        self.crf_inp.setGeometry(QtCore.QRect(190, 20, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.crf_inp.setFont(font)
        self.crf_inp.setObjectName("crf_inp")
        self.cmd_inp = QtWidgets.QLineEdit(self.parameter_group)
        self.cmd_inp.setGeometry(QtCore.QRect(130, 46, 451, 20))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.cmd_inp.setFont(font)
        self.cmd_inp.setObjectName("cmd_inp")
        self.cmd_label = QtWidgets.QLabel(self.parameter_group)
        self.cmd_label.setGeometry(QtCore.QRect(10, 50, 111, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmd_label.setFont(font)
        self.cmd_label.setObjectName("cmd_label")
        self.preset_dropdown = QtWidgets.QComboBox(self.parameter_group)
        self.preset_dropdown.setGeometry(QtCore.QRect(460, 20, 121, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.preset_dropdown.setFont(font)
        self.preset_dropdown.setMouseTracking(False)
        self.preset_dropdown.setObjectName("preset_dropdown")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(540, 10, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.output_group = QtWidgets.QGroupBox(self.centralwidget)
        self.output_group.setGeometry(QtCore.QRect(20, 280, 591, 101))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.output_group.setFont(font)
        self.output_group.setObjectName("output_group")
        self.output_folder_checkbox = QtWidgets.QCheckBox(self.output_group)
        self.output_folder_checkbox.setEnabled(True)
        self.output_folder_checkbox.setGeometry(QtCore.QRect(10, 20, 191, 17))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.output_folder_checkbox.setFont(font)
        self.output_folder_checkbox.setChecked(True)
        self.output_folder_checkbox.setObjectName("output_folder_checkbox")
        self.output_dropdown = QtWidgets.QComboBox(self.output_group)
        self.output_dropdown.setEnabled(False)
        self.output_dropdown.setGeometry(QtCore.QRect(10, 40, 491, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.output_dropdown.setFont(font)
        self.output_dropdown.setObjectName("output_dropdown")
        self.extension_label = QtWidgets.QLabel(self.output_group)
        self.extension_label.setGeometry(QtCore.QRect(380, 17, 71, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.extension_label.setFont(font)
        self.extension_label.setObjectName("extension_label")
        self.output_browse = QtWidgets.QPushButton(self.output_group)
        self.output_browse.setEnabled(False)
        self.output_browse.setGeometry(QtCore.QRect(510, 40, 75, 23))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.output_browse.setFont(font)
        self.output_browse.setObjectName("output_browse")
        self.extension_inp = QtWidgets.QLineEdit(self.output_group)
        self.extension_inp.setGeometry(QtCore.QRect(450, 20, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.extension_inp.setFont(font)
        self.extension_inp.setAlignment(QtCore.Qt.AlignCenter)
        self.extension_inp.setObjectName("extension_inp")
        self.resolution_label = QtWidgets.QLabel(self.output_group)
        self.resolution_label.setGeometry(QtCore.QRect(10, 70, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resolution_label.setFont(font)
        self.resolution_label.setObjectName("resolution_label")
        self.resolution_dropdown = QtWidgets.QComboBox(self.output_group)
        self.resolution_dropdown.setGeometry(QtCore.QRect(130, 70, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resolution_dropdown.setFont(font)
        self.resolution_dropdown.setObjectName("resolution_dropdown")
        self.original_resolution_label = QtWidgets.QLabel(self.output_group)
        self.original_resolution_label.setGeometry(QtCore.QRect(210, 70, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.original_resolution_label.setFont(font)
        self.original_resolution_label.setObjectName("original_resolution_label")
        self.overlay_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.overlay_checkbox.setEnabled(True)
        self.overlay_checkbox.setGeometry(QtCore.QRect(30, 570, 151, 17))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.overlay_checkbox.setFont(font)
        self.overlay_checkbox.setObjectName("overlay_checkbox")
        self.overlay_group = QtWidgets.QFrame(self.centralwidget)
        self.overlay_group.setEnabled(False)
        self.overlay_group.setGeometry(QtCore.QRect(30, 590, 571, 51))
        self.overlay_group.setFrameShape(QtWidgets.QFrame.Box)
        self.overlay_group.setFrameShadow(QtWidgets.QFrame.Raised)
        self.overlay_group.setObjectName("overlay_group")
        self.version_label = QtWidgets.QLabel(self.overlay_group)
        self.version_label.setGeometry(QtCore.QRect(420, 0, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.version_label.setFont(font)
        self.version_label.setObjectName("version_label")
        self.project_inp = QtWidgets.QLineEdit(self.overlay_group)
        self.project_inp.setGeometry(QtCore.QRect(30, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.project_inp.setFont(font)
        self.project_inp.setObjectName("project_inp")
        self.project_label = QtWidgets.QLabel(self.overlay_group)
        self.project_label.setGeometry(QtCore.QRect(30, 0, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.project_label.setFont(font)
        self.project_label.setObjectName("project_label")
        self.author_inp = QtWidgets.QLineEdit(self.overlay_group)
        self.author_inp.setGeometry(QtCore.QRect(160, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.author_inp.setFont(font)
        self.author_inp.setObjectName("author_inp")
        self.version_inp = QtWidgets.QLineEdit(self.overlay_group)
        self.version_inp.setGeometry(QtCore.QRect(420, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.version_inp.setFont(font)
        self.version_inp.setObjectName("version_inp")
        self.author_label = QtWidgets.QLabel(self.overlay_group)
        self.author_label.setGeometry(QtCore.QRect(160, 0, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.author_label.setFont(font)
        self.author_label.setObjectName("author_label")
        self.task_inp = QtWidgets.QLineEdit(self.overlay_group)
        self.task_inp.setGeometry(QtCore.QRect(290, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.task_inp.setFont(font)
        self.task_inp.setObjectName("task_inp")
        self.task_label = QtWidgets.QLabel(self.overlay_group)
        self.task_label.setGeometry(QtCore.QRect(290, 0, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.task_label.setFont(font)
        self.task_label.setObjectName("task_label")
        self.file_list = QtWidgets.QTableWidget(self.centralwidget)
        self.file_list.setGeometry(QtCore.QRect(20, 139, 591, 111))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.file_list.setFont(font)
        self.file_list.setObjectName("file_list")
        self.file_list.setColumnCount(0)
        self.file_list.setRowCount(0)
        self.input_browse = QtWidgets.QPushButton(self.centralwidget)
        self.input_browse.setEnabled(True)
        self.input_browse.setGeometry(QtCore.QRect(550, 250, 61, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_browse.setFont(font)
        self.input_browse.setObjectName("input_browse")
        converter.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(converter)
        self.statusbar.setObjectName("statusbar")
        converter.setStatusBar(self.statusbar)

        self.retranslateUi(converter)
        QtCore.QMetaObject.connectSlotsByName(converter)

    def retranslateUi(self, converter):
        _translate = QtCore.QCoreApplication.translate
        converter.setWindowTitle(_translate("converter", "Converter"))
        self.toolButton.setText(_translate("converter", "More Tool"))
        self.codec_group.setTitle(_translate("converter", "Codecs"))
        self.vcodec_label.setText(_translate("converter", "Video Codecs"))
        self.acodec_label.setText(_translate("converter", "Audio Codecs"))
        self.ETA_label.setText(_translate("converter", "ETA : "))
        self.update_label.setText(_translate("converter", "Update: 21/08/2019"))
        self.file_list_label.setText(_translate("converter", "File List"))
        self.time_label.setText(_translate("converter", "None"))
        self.convert_btn.setText(_translate("converter", "Convert"))
        self.close_btn.setText(_translate("converter", "Close"))
        self.logo_label.setText(_translate("converter", "<html><head/><body><p><img src=\":/logo_large/logo_large.png\"/></p></body></html>"))
        self.clear_btn.setText(_translate("converter", "Clear"))
        self.header_label.setText(_translate("converter", "video converter"))
        self.parameter_group.setTitle(_translate("converter", "Parameters"))
        self.frame_rate_label.setText(_translate("converter", "Frame Rate:"))
        self.frame_rate_inp.setText(_translate("converter", "(auto)"))
        self.audio_bitrate_label.setText(_translate("converter", "Audio-Bitrate:"))
        self.audio_bitrate_inp.setText(_translate("converter", "(auto)"))
        self.crf_label.setText(_translate("converter", "CRF:"))
        self.crf_inp.setText(_translate("converter", "(auto)"))
        self.cmd_inp.setText(_translate("converter", "(None)"))
        self.cmd_label.setText(_translate("converter", "CMD Parameters:"))
        self.label_3.setText(_translate("converter", "FFMPEG Core"))
        self.output_group.setTitle(_translate("converter", "Output"))
        self.output_folder_checkbox.setText(_translate("converter", "Output To Original Folder"))
        self.extension_label.setText(_translate("converter", "Extension :"))
        self.output_browse.setText(_translate("converter", "Browse"))
        self.extension_inp.setText(_translate("converter", "mov"))
        self.resolution_label.setText(_translate("converter", "Output Resolution:"))
        self.original_resolution_label.setText(_translate("converter", "of original resolution"))
        self.overlay_checkbox.setText(_translate("converter", "Use Overlay"))
        self.version_label.setText(_translate("converter", "Version"))
        self.project_label.setText(_translate("converter", "Project"))
        self.author_label.setText(_translate("converter", "Author"))
        self.task_label.setText(_translate("converter", "Task"))
        self.input_browse.setText(_translate("converter", "Browse"))


import logo_large_rc
