# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'overlay.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_overlay(object):
    def setupUi(self, overlay):
        overlay.setObjectName("overlay")
        overlay.setWindowModality(QtCore.Qt.ApplicationModal)
        overlay.resize(598, 438)
        overlay.setMinimumSize(QtCore.QSize(598, 438))
        overlay.setMaximumSize(QtCore.QSize(598, 438))
        self.centralwidget = QtWidgets.QWidget(overlay)
        self.centralwidget.setMinimumSize(QtCore.QSize(598, 418))
        self.centralwidget.setMaximumSize(QtCore.QSize(601, 418))
        self.centralwidget.setObjectName("centralwidget")
        self.convert_btn = QtWidgets.QPushButton(self.centralwidget)
        self.convert_btn.setEnabled(True)
        self.convert_btn.setGeometry(QtCore.QRect(510, 390, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.convert_btn.setFont(font)
        self.convert_btn.setObjectName("convert_btn")
        self.output_group = QtWidgets.QGroupBox(self.centralwidget)
        self.output_group.setGeometry(QtCore.QRect(0, 180, 601, 81))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.output_group.setFont(font)
        self.output_group.setTitle("")
        self.output_group.setObjectName("output_group")
        self.output_browse = QtWidgets.QPushButton(self.output_group)
        self.output_browse.setEnabled(False)
        self.output_browse.setGeometry(QtCore.QRect(510, 20, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.output_browse.setFont(font)
        self.output_browse.setObjectName("output_browse")
        self.output_dropdown = QtWidgets.QComboBox(self.output_group)
        self.output_dropdown.setEnabled(False)
        self.output_dropdown.setGeometry(QtCore.QRect(10, 20, 491, 22))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.output_dropdown.setFont(font)
        self.output_dropdown.setObjectName("output_dropdown")
        self.output_folder_checkbox = QtWidgets.QCheckBox(self.output_group)
        self.output_folder_checkbox.setEnabled(True)
        self.output_folder_checkbox.setGeometry(QtCore.QRect(10, 0, 191, 17))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.output_folder_checkbox.setFont(font)
        self.output_folder_checkbox.setChecked(True)
        self.output_folder_checkbox.setObjectName("output_folder_checkbox")
        self.extension_inp = QtWidgets.QLineEdit(self.output_group)
        self.extension_inp.setGeometry(QtCore.QRect(450, 0, 51, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.extension_inp.setFont(font)
        self.extension_inp.setObjectName("extension_inp")
        self.extension_label = QtWidgets.QLabel(self.output_group)
        self.extension_label.setGeometry(QtCore.QRect(380, -2, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.extension_label.setFont(font)
        self.extension_label.setObjectName("extension_label")
        self.original_resolution_label = QtWidgets.QLabel(self.output_group)
        self.original_resolution_label.setGeometry(QtCore.QRect(210, 50, 141, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.original_resolution_label.setFont(font)
        self.original_resolution_label.setObjectName("original_resolution_label")
        self.resolution_label = QtWidgets.QLabel(self.output_group)
        self.resolution_label.setGeometry(QtCore.QRect(10, 50, 121, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resolution_label.setFont(font)
        self.resolution_label.setObjectName("resolution_label")
        self.resolution_dropdown = QtWidgets.QComboBox(self.output_group)
        self.resolution_dropdown.setGeometry(QtCore.QRect(130, 50, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.resolution_dropdown.setFont(font)
        self.resolution_dropdown.setObjectName("resolution_dropdown")
        self.information_group = QtWidgets.QGroupBox(self.centralwidget)
        self.information_group.setGeometry(QtCore.QRect(10, 270, 441, 71))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.information_group.setFont(font)
        self.information_group.setObjectName("information_group")
        self.project_label = QtWidgets.QLabel(self.information_group)
        self.project_label.setGeometry(QtCore.QRect(10, 20, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.project_label.setFont(font)
        self.project_label.setObjectName("project_label")
        self.author_label = QtWidgets.QLabel(self.information_group)
        self.author_label.setGeometry(QtCore.QRect(120, 20, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.author_label.setFont(font)
        self.author_label.setObjectName("author_label")
        self.author_inp = QtWidgets.QLineEdit(self.information_group)
        self.author_inp.setGeometry(QtCore.QRect(120, 40, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.author_inp.setFont(font)
        self.author_inp.setObjectName("author_inp")
        self.task_label = QtWidgets.QLabel(self.information_group)
        self.task_label.setGeometry(QtCore.QRect(230, 20, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.task_label.setFont(font)
        self.task_label.setObjectName("task_label")
        self.project_inp = QtWidgets.QLineEdit(self.information_group)
        self.project_inp.setGeometry(QtCore.QRect(10, 40, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.project_inp.setFont(font)
        self.project_inp.setObjectName("project_inp")
        self.version_inp = QtWidgets.QLineEdit(self.information_group)
        self.version_inp.setGeometry(QtCore.QRect(340, 40, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.version_inp.setFont(font)
        self.version_inp.setObjectName("version_inp")
        self.version_label = QtWidgets.QLabel(self.information_group)
        self.version_label.setGeometry(QtCore.QRect(340, 20, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.version_label.setFont(font)
        self.version_label.setObjectName("version_label")
        self.task_inp = QtWidgets.QLineEdit(self.information_group)
        self.task_inp.setGeometry(QtCore.QRect(230, 40, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.task_inp.setFont(font)
        self.task_inp.setObjectName("task_inp")
        self.file_list_label = QtWidgets.QLabel(self.centralwidget)
        self.file_list_label.setGeometry(QtCore.QRect(10, 10, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.file_list_label.setFont(font)
        self.file_list_label.setObjectName("file_list_label")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(10, 140, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.clear_btn.setFont(font)
        self.clear_btn.setObjectName("clear_btn")
        self.close_btn = QtWidgets.QPushButton(self.centralwidget)
        self.close_btn.setGeometry(QtCore.QRect(10, 390, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.close_btn.setFont(font)
        self.close_btn.setObjectName("close_btn")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(510, 0, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton.setFont(font)
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.toolButton.setAcceptDrops(False)
        self.toolButton.setToolTip("")
        self.toolButton.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton.setObjectName("toolButton")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 350, 581, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.preser_group = QtWidgets.QGroupBox(self.centralwidget)
        self.preser_group.setGeometry(QtCore.QRect(460, 280, 121, 61))
        self.preser_group.setTitle("")
        self.preser_group.setObjectName("preser_group")
        self.preset_dropdown = QtWidgets.QComboBox(self.preser_group)
        self.preset_dropdown.setGeometry(QtCore.QRect(0, 30, 121, 22))
        self.preset_dropdown.setObjectName("preset_dropdown")
        self.preset_label = QtWidgets.QLabel(self.preser_group)
        self.preset_label.setGeometry(QtCore.QRect(0, 0, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.preset_label.setFont(font)
        self.preset_label.setObjectName("preset_label")
        self.update_label = QtWidgets.QLabel(self.centralwidget)
        self.update_label.setGeometry(QtCore.QRect(390, 0, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.update_label.setFont(font)
        self.update_label.setObjectName("update_label")
        self.file_list = QtWidgets.QListWidget(self.centralwidget)
        self.file_list.setGeometry(QtCore.QRect(10, 30, 571, 111))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        self.file_list.setFont(font)
        self.file_list.setObjectName("file_list")
        self.input_browse = QtWidgets.QPushButton(self.centralwidget)
        self.input_browse.setEnabled(True)
        self.input_browse.setGeometry(QtCore.QRect(520, 140, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_browse.setFont(font)
        self.input_browse.setObjectName("input_browse")
        overlay.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(overlay)
        self.statusbar.setObjectName("statusbar")
        overlay.setStatusBar(self.statusbar)

        self.retranslateUi(overlay)
        QtCore.QMetaObject.connectSlotsByName(overlay)

    def retranslateUi(self, overlay):
        _translate = QtCore.QCoreApplication.translate
        overlay.setWindowTitle(_translate("overlay", "Overlay"))
        self.convert_btn.setText(_translate("overlay", "Convert"))
        self.output_browse.setText(_translate("overlay", "Browse"))
        self.output_folder_checkbox.setText(_translate("overlay", "Output To Original Folder"))
        self.extension_inp.setText(_translate("overlay", "mov"))
        self.extension_label.setText(_translate("overlay", "Extension:"))
        self.original_resolution_label.setText(_translate("overlay", "of original resolution"))
        self.resolution_label.setText(_translate("overlay", "Output Resolution:"))
        self.information_group.setTitle(_translate("overlay", "Information"))
        self.project_label.setText(_translate("overlay", "Project"))
        self.author_label.setText(_translate("overlay", "Author"))
        self.task_label.setText(_translate("overlay", "Task"))
        self.version_label.setText(_translate("overlay", "Version"))
        self.file_list_label.setText(_translate("overlay", "File List"))
        self.clear_btn.setText(_translate("overlay", "clear"))
        self.close_btn.setText(_translate("overlay", "Close"))
        self.toolButton.setText(_translate("overlay", "More Tool"))
        self.preset_label.setText(_translate("overlay", "Presets"))
        self.update_label.setText(_translate("overlay", "Update: 21/08/2019"))
        self.input_browse.setText(_translate("overlay", "Browse"))


