# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'preset.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PreSetDialog(object):
    def setupUi(self, PreSetDialog):
        PreSetDialog.setObjectName("PreSetDialog")
        PreSetDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        PreSetDialog.resize(540, 331)
        PreSetDialog.setMinimumSize(QtCore.QSize(540, 331))
        PreSetDialog.setMaximumSize(QtCore.QSize(540, 331))
        self.groupBox = QtWidgets.QGroupBox(PreSetDialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 291, 281))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.audio_bitrate_label = QtWidgets.QLabel(self.groupBox)
        self.audio_bitrate_label.setGeometry(QtCore.QRect(10, 210, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.audio_bitrate_label.setFont(font)
        self.audio_bitrate_label.setObjectName("audio_bitrate_label")
        self.crf_label = QtWidgets.QLabel(self.groupBox)
        self.crf_label.setGeometry(QtCore.QRect(10, 180, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.crf_label.setFont(font)
        self.crf_label.setObjectName("crf_label")
        self.frame_rate_label = QtWidgets.QLabel(self.groupBox)
        self.frame_rate_label.setGeometry(QtCore.QRect(10, 150, 81, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.frame_rate_label.setFont(font)
        self.frame_rate_label.setObjectName("frame_rate_label")
        self.frame_rate_inp = QtWidgets.QLineEdit(self.groupBox)
        self.frame_rate_inp.setGeometry(QtCore.QRect(110, 150, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.frame_rate_inp.setFont(font)
        self.frame_rate_inp.setObjectName("frame_rate_inp")
        self.crf_inp = QtWidgets.QLineEdit(self.groupBox)
        self.crf_inp.setEnabled(False)
        self.crf_inp.setGeometry(QtCore.QRect(220, 180, 61, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.crf_inp.setFont(font)
        self.crf_inp.setObjectName("crf_inp")
        self.audio_bitrate_inp = QtWidgets.QLineEdit(self.groupBox)
        self.audio_bitrate_inp.setGeometry(QtCore.QRect(110, 210, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.audio_bitrate_inp.setFont(font)
        self.audio_bitrate_inp.setObjectName("audio_bitrate_inp")
        self.preset_name_label = QtWidgets.QLabel(self.groupBox)
        self.preset_name_label.setGeometry(QtCore.QRect(10, 120, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.preset_name_label.setFont(font)
        self.preset_name_label.setObjectName("preset_name_label")
        self.preset_name_inp = QtWidgets.QLineEdit(self.groupBox)
        self.preset_name_inp.setGeometry(QtCore.QRect(110, 120, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.preset_name_inp.setFont(font)
        self.preset_name_inp.setObjectName("preset_name_inp")
        self.clear_btn = QtWidgets.QPushButton(self.groupBox)
        self.clear_btn.setGeometry(QtCore.QRect(150, 250, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.clear_btn.setFont(font)
        self.clear_btn.setObjectName("clear_btn")
        self.save_btn = QtWidgets.QPushButton(self.groupBox)
        self.save_btn.setGeometry(QtCore.QRect(10, 250, 51, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.save_btn.setFont(font)
        self.save_btn.setObjectName("save_btn")
        self.acodec_label = QtWidgets.QLabel(self.groupBox)
        self.acodec_label.setGeometry(QtCore.QRect(10, 60, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.acodec_label.setFont(font)
        self.acodec_label.setObjectName("acodec_label")
        self.vcodec_label = QtWidgets.QLabel(self.groupBox)
        self.vcodec_label.setGeometry(QtCore.QRect(10, 20, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.vcodec_label.setFont(font)
        self.vcodec_label.setObjectName("vcodec_label")
        self.acodecs_dropdown = QtWidgets.QComboBox(self.groupBox)
        self.acodecs_dropdown.setGeometry(QtCore.QRect(10, 80, 271, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.acodecs_dropdown.setFont(font)
        self.acodecs_dropdown.setObjectName("acodecs_dropdown")
        self.vcodecs_dropdown = QtWidgets.QComboBox(self.groupBox)
        self.vcodecs_dropdown.setGeometry(QtCore.QRect(10, 40, 271, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.vcodecs_dropdown.setFont(font)
        self.vcodecs_dropdown.setObjectName("vcodecs_dropdown")
        self.crf_dropdown_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.crf_dropdown_radioButton.setGeometry(QtCore.QRect(90, 185, 13, 13))
        self.crf_dropdown_radioButton.setText("")
        self.crf_dropdown_radioButton.setChecked(True)
        self.crf_dropdown_radioButton.setObjectName("crf_dropdown_radioButton")
        self.crf_inp_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.crf_inp_radioButton.setGeometry(QtCore.QRect(200, 185, 13, 13))
        self.crf_inp_radioButton.setText("")
        self.crf_inp_radioButton.setObjectName("crf_inp_radioButton")
        self.crf_dropdown = QtWidgets.QComboBox(self.groupBox)
        self.crf_dropdown.setGeometry(QtCore.QRect(110, 180, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.crf_dropdown.setFont(font)
        self.crf_dropdown.setObjectName("crf_dropdown")
        self.preset_list = QtWidgets.QListWidget(PreSetDialog)
        self.preset_list.setGeometry(QtCore.QRect(310, 30, 211, 231))
        self.preset_list.setObjectName("preset_list")
        self.preset_list_label = QtWidgets.QLabel(PreSetDialog)
        self.preset_list_label.setGeometry(QtCore.QRect(310, 10, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.preset_list_label.setFont(font)
        self.preset_list_label.setObjectName("preset_list_label")
        self.delete_btn = QtWidgets.QPushButton(PreSetDialog)
        self.delete_btn.setGeometry(QtCore.QRect(460, 270, 61, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delete_btn.setFont(font)
        self.delete_btn.setObjectName("delete_btn")
        self.close_btn = QtWidgets.QPushButton(PreSetDialog)
        self.close_btn.setGeometry(QtCore.QRect(10, 300, 61, 25))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.close_btn.setFont(font)
        self.close_btn.setObjectName("close_btn")

        self.retranslateUi(PreSetDialog)
        self.close_btn.clicked.connect(PreSetDialog.close)
        QtCore.QMetaObject.connectSlotsByName(PreSetDialog)

    def retranslateUi(self, PreSetDialog):
        _translate = QtCore.QCoreApplication.translate
        PreSetDialog.setWindowTitle(_translate("PreSetDialog", "Pre Set"))
        self.groupBox.setTitle(_translate("PreSetDialog", "Parameters"))
        self.audio_bitrate_label.setText(_translate("PreSetDialog", "Audio-Bitrate ："))
        self.crf_label.setText(_translate("PreSetDialog", "CRF :"))
        self.frame_rate_label.setText(_translate("PreSetDialog", "Frame Rate ："))
        self.preset_name_label.setText(_translate("PreSetDialog", "Pre-Set Name :"))
        self.clear_btn.setText(_translate("PreSetDialog", "Clear"))
        self.save_btn.setText(_translate("PreSetDialog", "Save"))
        self.acodec_label.setText(_translate("PreSetDialog", "Audio Codecs"))
        self.vcodec_label.setText(_translate("PreSetDialog", "Video Codecs"))
        self.preset_list_label.setText(_translate("PreSetDialog", "Pre-Set List"))
        self.delete_btn.setText(_translate("PreSetDialog", "Delete"))
        self.close_btn.setText(_translate("PreSetDialog", "Close"))


