# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'splice.ui'
#
# Created by: PyQt5 UI code generator 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Splice(object):
    def setupUi(self, Splice):
        Splice.setObjectName("Splice")
        Splice.setWindowModality(QtCore.Qt.ApplicationModal)
        Splice.resize(574, 431)
        Splice.setMinimumSize(QtCore.QSize(574, 431))
        Splice.setMaximumSize(QtCore.QSize(574, 431))
        Splice.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(Splice)
        self.centralwidget.setMinimumSize(QtCore.QSize(574, 411))
        self.centralwidget.setMaximumSize(QtCore.QSize(574, 411))
        self.centralwidget.setObjectName("centralwidget")
        self.update_label = QtWidgets.QLabel(self.centralwidget)
        self.update_label.setGeometry(QtCore.QRect(370, 10, 111, 20))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.update_label.setFont(font)
        self.update_label.setObjectName("update_label")
        self.toolButton = QtWidgets.QToolButton(self.centralwidget)
        self.toolButton.setGeometry(QtCore.QRect(490, 10, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.toolButton.setFont(font)
        self.toolButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.toolButton.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.toolButton.setAcceptDrops(False)
        self.toolButton.setToolTip("")
        self.toolButton.setPopupMode(QtWidgets.QToolButton.MenuButtonPopup)
        self.toolButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.toolButton.setAutoRaise(True)
        self.toolButton.setArrowType(QtCore.Qt.NoArrow)
        self.toolButton.setObjectName("toolButton")
        self.clear_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_btn.setGeometry(QtCore.QRect(80, 190, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.clear_btn.setFont(font)
        self.clear_btn.setObjectName("clear_btn")
        self.file_list_label = QtWidgets.QLabel(self.centralwidget)
        self.file_list_label.setGeometry(QtCore.QRect(10, 29, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.file_list_label.setFont(font)
        self.file_list_label.setObjectName("file_list_label")
        self.close_btn = QtWidgets.QPushButton(self.centralwidget)
        self.close_btn.setGeometry(QtCore.QRect(10, 380, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.close_btn.setFont(font)
        self.close_btn.setObjectName("close_btn")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(10, 350, 551, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(10, 190, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.delete_btn.setFont(font)
        self.delete_btn.setObjectName("delete_btn")
        self.up_btn = QtWidgets.QPushButton(self.centralwidget)
        self.up_btn.setGeometry(QtCore.QRect(440, 50, 21, 23))
        self.up_btn.setObjectName("up_btn")
        self.down_btn = QtWidgets.QPushButton(self.centralwidget)
        self.down_btn.setGeometry(QtCore.QRect(440, 170, 21, 23))
        self.down_btn.setObjectName("down_btn")
        self.splice_btn = QtWidgets.QPushButton(self.centralwidget)
        self.splice_btn.setEnabled(True)
        self.splice_btn.setGeometry(QtCore.QRect(480, 380, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.splice_btn.setFont(font)
        self.splice_btn.setObjectName("splice_btn")
        self.duration_inp = QtWidgets.QLineEdit(self.centralwidget)
        self.duration_inp.setEnabled(False)
        self.duration_inp.setGeometry(QtCore.QRect(370, 29, 51, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.duration_inp.setFont(font)
        self.duration_inp.setText("")
        self.duration_inp.setObjectName("duration_inp")
        self.ok_btn = QtWidgets.QPushButton(self.centralwidget)
        self.ok_btn.setEnabled(False)
        self.ok_btn.setGeometry(QtCore.QRect(430, 30, 31, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.ok_btn.setFont(font)
        self.ok_btn.setObjectName("ok_btn")
        self.image_duration_label = QtWidgets.QLabel(self.centralwidget)
        self.image_duration_label.setGeometry(QtCore.QRect(270, 30, 101, 18))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.image_duration_label.setFont(font)
        self.image_duration_label.setObjectName("image_duration_label")
        self.preser_group = QtWidgets.QGroupBox(self.centralwidget)
        self.preser_group.setGeometry(QtCore.QRect(460, 50, 111, 141))
        self.preser_group.setTitle("")
        self.preser_group.setObjectName("preser_group")
        self.preset_dropdown = QtWidgets.QComboBox(self.preser_group)
        self.preset_dropdown.setGeometry(QtCore.QRect(10, 20, 91, 22))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.preset_dropdown.setFont(font)
        self.preset_dropdown.setObjectName("preset_dropdown")
        self.preset_label = QtWidgets.QLabel(self.preser_group)
        self.preset_label.setGeometry(QtCore.QRect(10, 0, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.preset_label.setFont(font)
        self.preset_label.setObjectName("preset_label")
        self.resolution_label = QtWidgets.QLabel(self.preser_group)
        self.resolution_label.setGeometry(QtCore.QRect(10, 60, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.resolution_label.setFont(font)
        self.resolution_label.setObjectName("resolution_label")
        self.w_inp = QtWidgets.QLineEdit(self.preser_group)
        self.w_inp.setGeometry(QtCore.QRect(30, 80, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.w_inp.setFont(font)
        self.w_inp.setObjectName("w_inp")
        self.h_inp = QtWidgets.QLineEdit(self.preser_group)
        self.h_inp.setGeometry(QtCore.QRect(30, 110, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.h_inp.setFont(font)
        self.h_inp.setObjectName("h_inp")
        self.w_label = QtWidgets.QLabel(self.preser_group)
        self.w_label.setGeometry(QtCore.QRect(10, 80, 16, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.w_label.setFont(font)
        self.w_label.setObjectName("w_label")
        self.h_label = QtWidgets.QLabel(self.preser_group)
        self.h_label.setGeometry(QtCore.QRect(14, 110, 16, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.h_label.setFont(font)
        self.h_label.setObjectName("h_label")
        self.output_group = QtWidgets.QGroupBox(self.centralwidget)
        self.output_group.setGeometry(QtCore.QRect(0, 220, 581, 51))
        self.output_group.setTitle("")
        self.output_group.setObjectName("output_group")
        self.output_label = QtWidgets.QLabel(self.output_group)
        self.output_label.setGeometry(QtCore.QRect(10, 0, 61, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.output_label.setFont(font)
        self.output_label.setObjectName("output_label")
        self.output_browse = QtWidgets.QPushButton(self.output_group)
        self.output_browse.setEnabled(True)
        self.output_browse.setGeometry(QtCore.QRect(490, 20, 75, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.output_browse.setFont(font)
        self.output_browse.setObjectName("output_browse")
        self.output_dropdown = QtWidgets.QComboBox(self.output_group)
        self.output_dropdown.setEnabled(True)
        self.output_dropdown.setGeometry(QtCore.QRect(10, 20, 471, 22))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.output_dropdown.setFont(font)
        self.output_dropdown.setObjectName("output_dropdown")
        self.overlay_checkbox = QtWidgets.QCheckBox(self.centralwidget)
        self.overlay_checkbox.setEnabled(True)
        self.overlay_checkbox.setGeometry(QtCore.QRect(10, 270, 101, 17))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setBold(True)
        font.setWeight(75)
        self.overlay_checkbox.setFont(font)
        self.overlay_checkbox.setObjectName("overlay_checkbox")
        self.file_list = QtWidgets.QTableWidget(self.centralwidget)
        self.file_list.setGeometry(QtCore.QRect(10, 50, 431, 141))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(8)
        self.file_list.setFont(font)
        self.file_list.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.file_list.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContentsOnFirstShow)
        self.file_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.file_list.setProperty("showDropIndicator", True)
        self.file_list.setDragEnabled(False)
        self.file_list.setDragDropOverwriteMode(False)
        self.file_list.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.file_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.file_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.file_list.setGridStyle(QtCore.Qt.NoPen)
        self.file_list.setRowCount(0)
        self.file_list.setColumnCount(2)
        self.file_list.setObjectName("file_list")
        self.file_list.horizontalHeader().setVisible(True)
        self.file_list.horizontalHeader().setCascadingSectionResizes(False)
        self.file_list.horizontalHeader().setDefaultSectionSize(90)
        self.file_list.horizontalHeader().setHighlightSections(True)
        self.file_list.horizontalHeader().setMinimumSectionSize(100)
        self.file_list.horizontalHeader().setSortIndicatorShown(False)
        self.file_list.horizontalHeader().setStretchLastSection(True)
        self.file_list.verticalHeader().setDefaultSectionSize(20)
        self.file_list.verticalHeader().setMinimumSectionSize(20)
        self.file_list.verticalHeader().setStretchLastSection(False)
        self.clear_all_btn = QtWidgets.QPushButton(self.centralwidget)
        self.clear_all_btn.setEnabled(True)
        self.clear_all_btn.setGeometry(QtCore.QRect(380, 380, 81, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.clear_all_btn.setFont(font)
        self.clear_all_btn.setObjectName("clear_all_btn")
        self.input_browse = QtWidgets.QPushButton(self.centralwidget)
        self.input_browse.setEnabled(True)
        self.input_browse.setGeometry(QtCore.QRect(380, 190, 61, 23))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.input_browse.setFont(font)
        self.input_browse.setObjectName("input_browse")
        self.overlay_group = QtWidgets.QGroupBox(self.centralwidget)
        self.overlay_group.setEnabled(False)
        self.overlay_group.setGeometry(QtCore.QRect(0, 290, 571, 51))
        self.overlay_group.setTitle("")
        self.overlay_group.setObjectName("overlay_group")
        self.version_label = QtWidgets.QLabel(self.overlay_group)
        self.version_label.setGeometry(QtCore.QRect(410, 0, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.version_label.setFont(font)
        self.version_label.setObjectName("version_label")
        self.project_label = QtWidgets.QLabel(self.overlay_group)
        self.project_label.setGeometry(QtCore.QRect(20, 0, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.project_label.setFont(font)
        self.project_label.setObjectName("project_label")
        self.author_label = QtWidgets.QLabel(self.overlay_group)
        self.author_label.setGeometry(QtCore.QRect(150, 0, 61, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.author_label.setFont(font)
        self.author_label.setObjectName("author_label")
        self.task_inp = QtWidgets.QLineEdit(self.overlay_group)
        self.task_inp.setGeometry(QtCore.QRect(280, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.task_inp.setFont(font)
        self.task_inp.setObjectName("task_inp")
        self.task_label = QtWidgets.QLabel(self.overlay_group)
        self.task_label.setGeometry(QtCore.QRect(280, 0, 51, 21))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.task_label.setFont(font)
        self.task_label.setObjectName("task_label")
        self.project_inp = QtWidgets.QLineEdit(self.overlay_group)
        self.project_inp.setGeometry(QtCore.QRect(20, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.project_inp.setFont(font)
        self.project_inp.setObjectName("project_inp")
        self.version_inp = QtWidgets.QLineEdit(self.overlay_group)
        self.version_inp.setGeometry(QtCore.QRect(410, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.version_inp.setFont(font)
        self.version_inp.setObjectName("version_inp")
        self.author_inp = QtWidgets.QLineEdit(self.overlay_group)
        self.author_inp.setGeometry(QtCore.QRect(150, 20, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.author_inp.setFont(font)
        self.author_inp.setObjectName("author_inp")
        Splice.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Splice)
        self.statusbar.setObjectName("statusbar")
        Splice.setStatusBar(self.statusbar)

        self.retranslateUi(Splice)
        QtCore.QMetaObject.connectSlotsByName(Splice)

    def retranslateUi(self, Splice):
        _translate = QtCore.QCoreApplication.translate
        Splice.setWindowTitle(_translate("Splice", "Splice"))
        self.update_label.setText(_translate("Splice", "Update: 05/08/2019"))
        self.toolButton.setText(_translate("Splice", "More Tool"))
        self.clear_btn.setText(_translate("Splice", "Clear"))
        self.file_list_label.setText(_translate("Splice", "File List"))
        self.close_btn.setText(_translate("Splice", "Close"))
        self.delete_btn.setText(_translate("Splice", "Delete"))
        self.up_btn.setText(_translate("Splice", "↑"))
        self.down_btn.setText(_translate("Splice", "↓"))
        self.splice_btn.setText(_translate("Splice", "Splice"))
        self.ok_btn.setText(_translate("Splice", "OK"))
        self.image_duration_label.setText(_translate("Splice", "Image Duration:"))
        self.preset_label.setText(_translate("Splice", "Presets"))
        self.resolution_label.setText(_translate("Splice", "Resolution"))
        self.w_inp.setText(_translate("Splice", "1920"))
        self.h_inp.setText(_translate("Splice", "1080"))
        self.w_label.setText(_translate("Splice", "W:"))
        self.h_label.setText(_translate("Splice", "H:"))
        self.output_label.setText(_translate("Splice", "Output"))
        self.output_browse.setText(_translate("Splice", "Browse"))
        self.overlay_checkbox.setText(_translate("Splice", "Use Overlay"))
        self.clear_all_btn.setText(_translate("Splice", "Clear"))
        self.input_browse.setText(_translate("Splice", "Browse"))
        self.version_label.setText(_translate("Splice", "Version"))
        self.project_label.setText(_translate("Splice", "Project"))
        self.author_label.setText(_translate("Splice", "Author"))
        self.task_label.setText(_translate("Splice", "Task"))


